apiVersion: v1
kind: Pod
metadata:
  name:   ubuntu
spec:
  containers:
    - name:    ubuntu
      image: ubuntu:latest
      args: [bash, -c, 'for ((i = 0; ; i++)); do echo "$i: $(date)"; sleep 100; done']
